version: '2'
services:
  web-dev:
    build: .
    ports:
     - "5000:5000"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/dev
    depends_on:
     - mongo 
    links:
     - mongo 
    volumes:
     - .:/app
    command:
        ['npm', 'run', 'start']
  web-prod:
    build: .
    ports:
     - "5000:5000"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/prod
    volumes:
     - .:/app
    command:
        ['npm', 'run', 'start']
  mongo:
    image: mongo:3.4